//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTDLS.Katzebase.SQLServerMigration.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NTDLS.Katzebase.SQLServerMigration.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Login {
            get {
                object obj = ResourceManager.GetObject("Login", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///    i.name AS IndexName,
        ///    case when i.is_unique = 1 OR i.is_unique_constraint = 1 THEN 1 else 0 end IsUnique,
        ///    c.name AS ColumnName 
        ///FROM 
        ///    sys.indexes i
        ///    INNER JOIN sys.index_columns ic ON i.object_id = ic.object_id AND i.index_id = ic.index_id
        ///    INNER JOIN sys.columns c ON ic.object_id = c.object_id AND ic.column_id = c.column_id
        ///    INNER JOIN sys.tables t ON i.object_id = t.object_id
        ///WHERE 
        ///    i.is_disabled = 0  -- Exclude disabled indexes
        /// AND ic.is_included_column = 0
        /// AND &apos;[&apos; + [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SqlGetObjectIndexes {
            get {
                return ResourceManager.GetString("SqlGetObjectIndexes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///    &apos;[&apos; + OBJECT_SCHEMA_NAME(SysT.[object_id]) + &apos;].[&apos; + SysT.[name] +&apos;]&apos; AS [SourceSchemaObject],
        ///    OBJECT_SCHEMA_NAME(SysT.[object_id]) + &apos;:&apos; + SysT.[name] AS [TargetSchemaObject], 
        ///    SysT.[name] AS [TargetObject],
        ///    ISNULL(SUM(p.reserved_page_count) * 8 * 1024, 0) AS TotalSizeBytes,  -- Total size in bytes
        ///    ISNULL(SUM(p.row_count), 0) AS TotalRows,                            -- Total rows
        ///    CASE 
        ///        WHEN SUM(p.row_count) &gt; 0 THEN (SUM(p.reserved_page_count) * 8 * 1024) / SUM(p.row [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SqlGetObjectsAndSizes {
            get {
                return ResourceManager.GetString("SqlGetObjectsAndSizes", resourceCulture);
            }
        }
    }
}
