name .NET Core Tests

on
  push
    branches
      - main

jobs
  build
    runs-on ubuntu-latest
    steps
      - name Checkout code
        uses actionscheckout@v2
      - name Setup .NET
        uses actionssetup-dotnet@v2
        with
          dotnet-version '8.0'
      - name Restore dependencies
        run dotnet restore
      - name Run Tests
        run dotnet test --no-restore --verbosity normal
